name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Prepare Hiero Solo
        id: solo
        uses: hiero-ledger/hiero-solo-action@a39acf8cfbaa2feb195a86530d0ab643a45aa541 # v0.10
        with:
          installMirrorNode: true
          hieroVersion: v0.63.7

      - name: Wait for Mirror Node
        run: |
          echo "Waiting for Mirror Node to be ready on http://localhost:8080..."
          until curl --output /dev/null --silent --head --fail http://localhost:8080/api/v1/health; do
            echo "Mirror Node not ready, waiting..."
            sleep 5
          done
          echo "Mirror Node is ready!"

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: solo
          HEDERA_ACCOUNT_ID: ${{ steps.solo.outputs.accountId }}
          HEDERA_PRIVATE_KEY: ${{ steps.solo.outputs.privateKey }}
          HEDERA_NETWORK: hiero-solo-action
          MIRROR_NODE_URL: http://localhost:8080
        run: ./mvnw verify -B -e -X
